paths:
  # Train, Val, Test CSV
  csv_root_path: "/workspace/DiffuAug/metadata/classification/aug_csv/0.8_0.1_0.1_balanced_200+50+50"
  train_csv_path: "/workspace/DiffuAug/metadata/classification/aug_csv/0.8_0.1_0.1_balanced_200+50+50/train_dataset.csv"
  val_csv_path: "/workspace/DiffuAug/metadata/classification/csv/0.8_0.1_0.1_balanced_200/val_dataset.csv"
  test_csv_path: "/workspace/DiffuAug/metadata/classification/csv/0.8_0.1_0.1_balanced_200/test_dataset.csv"

  # exp_result_path
  exp_path: "/data/results/classification/exps/no_aug/balanced"

  
params:
  task: train
  objective: 64x64 image classification
  img_size: 64
  lr: 0.0001
  channels: 1
  batch_size: 32
  epochs: 50
  threshold: 0.5