paths:
  # Train, Val, Test CSV
  csv_root_path: "/workspace/DiffuAug/metadata/classification/patient_csv/patient100/balanced_class/0.8_0.1_0.1"

  train_csv_path: "/workspace/DiffuAug/metadata/classification/patient_csv/patient100/aug_csv/ddim/p_uncond_0.2/aug_train_ddim_w_0.2.csv"
  val_csv_path: "/workspace/DiffuAug/metadata/classification/patient_csv/patient100/balanced_class/0.8_0.1_0.1/val_dataset.csv"
  test_csv_path: "/workspace/DiffuAug/metadata/classification/patient_csv/patient100/balanced_class/0.8_0.1_0.1/test_dataset.csv"

  # exp_result_path
  exp_path: "/data/results/classification/exps/aug/patients/ddim/p_uncond_0.2/differ_w/w_0.2"
  
params:
  task: train
  objective: 64x64 image classification
  img_size: 64
  lr: 0.0001
  channels: 1
  batch_size: 32
  epochs: 50
  threshold: 0.5