paths:
  # Train, Val, Test CSV
  csv_root_path: "/workspace/DiffuAug/metadata/classification/slice_csv/0.8_0.1_0.1_balanced_200"

  # exp_result_path
  exp_path: "/data/results/classification/exps/no_aug/slices/balanced/original/total_200"
  
params:
  task: train
  objective: 64x64 image classification
  img_size: 64
  lr: 0.0001
  channels: 1
  batch_size: 32
  epochs: 50
  threshold: 0.5