paths:
  model_path: "/data/results/generation/exps/cfg_exps/t500/models/69_fianl_ckpt.pth"
  sampling_path: "/data/results/generation/sampling/cfg/sampling_imgs/ddim/p_uncond_0.2/w_0.0"

information:
  img_size: 64
  timesteps: 500
  p_uncond: 0.2

params:
  task: train
  objective: 64x64 image generation
  img_size: 64
  learning_rate: 0.0001
  timesteps: 500
  channels: 1
  init_channels: 96
  dim_mults: [1, 2, 2]

generation:
  gen_img_num: 64

cfg_params:
  sampling_class_num: 1
  class_num: 2
  w: 0.0

log:
  verbose: "info" # "Verbose level: info | debug | warning | critical",