paths:
  # Train, Val, Test CSV
  csv_root_path: "/workspace/DiffuAug/metadata/classification/csv/0.8_0.1_0.1_balanced_200"

  # exp_result_path
  model_save_path: "/data/results/classification/model_weights"
  test_predict_result_save_path: "/data/results/classification/predicted_csv/resnet18"

  
params:
  task: train
  objective: 64x64 image classification
  img_size: 64
  lr: 0.0001
  channels: 1
  batch_size: 32
  epochs: 50
  threshold: 0.5