paths:
  # Training, Test CSV
  train_csv_path: "/workspace/DiffusionForBreastMRI/srcs/classification/csv/original_train_csv/train_dataset.csv"
  val_csv_path: "/workspace/DiffusionForBreastMRI/srcs/classification/csv/original_train_csv/val_dataset.csv"
  test_csv_path: "/workspace/DiffusionForBreastMRI/srcs/classification/csv/original_train_csv/test_dataset.csv"

  # exp_result_path
  model_save_path: "/workspace/DiffusionForBreastMRI/srcs/classification/results/models_file/original"
  test_predict_result_save_path: "/workspace/DiffusionForBreastMRI/srcs/classification/results/predict_results/original"

  
params:
  task: train
  objective: 64x64 image classification
  img_size: 64
  lr: 0.0001
  channels: 1
  batch_size: 32
  epochs: 50
  threshold: 0.5